/*
 * Strava API v3
 *
 * Strava API
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// A pair of latitude/longitude coordinates, represented as an array of 2 floating point numbers.

// See https://groups.google.com/forum/#!topic/strava-api/0EBIhSSsAws
type LatLng []float32
